# A generic, single database configuration.

[alembic]
# Path to migration scripts.
# this is typically a path given in POSIX (e.g. forward slashes), relative to the
# project root.
script_location = alembic

# template used to generate migration files.
# When creating a new migration file, the migration name will be added between
# the two % (rev)s identifiers, and the slug is generated automatically.
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(rev)s_%%(slug)s

# sys.path path, will be appended to PYTHONPATH if defined.
# Default value is `[]` which means path is taken from the script location.
prepend_sys_path = .

# Timezone for creating the migration files.
# Leave blank for the default behavior (UTC).
timezone = Asia/Shanghai

# max length of generated migration filename.
#truncate_slug_length = 40

# set to 'true' to run during testing.
# In migrations that don't need a real database (e.g. unit-test style), set
# this so Alembic's use of Engine is contained.
#needs_external_lock = false

# version path separator; defaults to double semicolon.
#upgrade_hooks = ...
#downgrade_hooks = ...

# timezone for run stamp.
run_stamp = true


[post_write_hooks]

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
